### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by yonderblue** [lanrat/extsort#3]
Would you consider changing your license to MIT?

**Comment by lanrat** [comment]
Can you elaborate a little on your reason for this request and your use case for this library that needs it?

**Comment by yonderblue** [comment]
I'd like to use this in some closed source code at work. If you are not up for the change I'll move on, but you might get contributions back if you change 👍

**Comment by lanrat** [comment]
Closing this issue since the attached PR was also closed.

**Comment by Andreas5739738** [comment]
Hi, @lanrat, would you be able to release a new version with the changed license? This would make importing easier. Thank you!

**Comment by lanrat** [comment]
Hello @Andreas5739738,

Similar to the prior request, can you elaborate a little on your reason for this request and your use case for this library that needs it?

**Comment by Andreas5739738** [comment]
I noticed that the released version is still licensed as GPLv3. It is the only GPL-licensed dependency of https://github.com/peak/s5cmd. To build a GPL-free version of s5cmd without having to depend on git revisions, having the Apache-licensed version of extsort released and versioned would be very helpful.

**Comment by Andreas5739738** [comment]
To clarify further: go.dev (https://pkg.go.dev/github.com/lanrat/extsort) still lists the package as licensed as GPL v3. So just depending on extsort will pull in the GPLv3-licensed package. Thanks!
