### ISSUE TITLE
Please create new release tag

### ISSUE THREAD

**Issue by gkowarzyk** [lanrat/extsort#6]
Hello,

I've noticed that the license has changed from GPL to Apache v2 on the `master` branch.
Nevertheless, there is currently only one release tag, `v1.0.0`, which still bundles a GPL license.

Could you please create a new release tag that includes the latest code and license from the `master` branch please?

Thanks in advance!

**Comment by lanrat** [comment]
Thanks for catching that. Fixed!

https://github.com/lanrat/extsort/releases/tag/v1.0.1
